---
- name: Install dependencies for rbenv (Debian/Ubuntu)
  apt: pkg=git
  when: ansible_os_family == "Debian"
  tags: rbenv

- name: Install dependencies for rbenv (RedHat/CentOS)
  yum: name=git
  when: ansible_os_family == "RedHat"
  tags: rbenv

- name: Install rbenv
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv version={{ rbenv.version }}
  tags: rbenv

- name: Add ~.rbenv/bin to PATH
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  lineinfile: >
    dest="~/.bash_profile"
    line="export PATH=$HOME/.rbenv/bin:$PATH"
    create=yes
  tags: rbenv

- name: Eval rbenv init in ~/.bash_profile
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  lineinfile: >
    dest="~/.bash_profile"
    line="eval \"$(rbenv init -)\""
    create=yes
  tags: rbenv

- name: Copy .gemrc to ~/.gemrc
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  copy: src={{ item }} dest=~/.gemrc
  with_first_found:
    - ../../../files/.gemrc
    - .gemrc
  tags: rbenv

- name: Install dependencies for ruby-build (Debian/Ubuntu)
  apt: pkg="{{ item }}"
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
  when: ansible_os_family == "Debian"
  tags: rbenv

- name: Install dependencies for ruby-build (RedHat/CentOS)
  yum:
    name: "{{ item }}"
  with_items:
    - gcc
    - openssl-devel
    - libyaml-devel
    - libffi-devel
    - readline-devel
    - zlib-devel
    - gdbm-devel
    - ncurses-devel
  when: ansible_os_family == "RedHat"
  tags: rbenv

- name: Install ruby-build as rbenv plugin
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
  tags: rbenv

- name: Check if {{ rbenv.ruby_version }} is installed
  shell: "sudo -iu {{ rbenv.user }} rbenv versions | grep {{ rbenv.ruby_version }}"
  register: rbenv_check_install
  changed_when: False
  ignore_errors: True
  tags: rbenv

- name: "Install {{ rbenv.ruby_version }}"
  command: "sudo -iu {{ rbenv.user }} rbenv install {{ rbenv.ruby_version }}"
  when: rbenv_check_install|failed
  tags: rbenv

- name: "Check if {{ rbenv.ruby_version }} is the default ruby version"
  shell: "sudo -iu {{ rbenv.user }} rbenv version | grep {{ rbenv.ruby_version }}"
  register: rbenv_check_default
  changed_when: False
  ignore_errors: True
  tags: rbenv

- name: "Set default ruby version to {{ rbenv.ruby_version }}"
  command: "sudo -iu {{ rbenv.user }} rbenv global {{ rbenv.ruby_version }}"
  when: rbenv_check_default|failed
  tags: rbenv
